### ISSUE TITLE
client does not authenticate with a rhythm server consistently

### ISSUE THREAD

**Issue by dcalacci** [HumanDynamics/rhythm-rtc#12]
This could be an issue with the client-side code, or with the rhythm server.

Check to see that we aren't introducing any race conditions in the client side. We should be doing one of two strategies:
1. start the chat immediately, and then wait to authenticate in a background thread. When authenticated, then attach the Sibilant process to the web audio stream.
2. wait to show users' video until the client authenticates with the server

let's try to focus on (1) for now.

**Comment by sarahkemi** [comment]
can we close this as well?
