### ISSUE TITLE
stun servers don't work

### ISSUE THREAD

**Issue by sarahkemi** [HumanDynamics/rhythm-rtc#15]
So it turns out that the google stun servers aren't working anymore, and most of the lists out there are from 2014 and not updated very frequently. I'm on the lookout for working stun servers, but the search has yet to be fruitful.

**Comment by dcalacci** [comment]
Hm, OK. 

Could you try setting up Twilio's Network Traversal Service?

Their STUN servers appear to be free, and their TURN servers are cheap enough for us to use:

https://www.twilio.com/stun-turn/pricing

**Comment by dcalacci** [comment]
Another alternative is: 

https://xirsys.com/technology/

I'd try Twilio first, though ☎️

**Comment by sarahkemi** [comment]
Twilio is AWESOME, all fixed!!
